version: 3.1.6.{build}
skip_tags: true
image: Visual Studio 2017 Preview
configuration: Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

before_build:
- cmd: >-
    dotnet restore
    
    nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal

test: off

deploy:
- provider: GitHub
  auth_token:
    secure: C84vi0K9LH3m0DN0dITWoJ09qb3sAcyqqkHsWWUE8EAlC2Xj7p9G+VcPVDKqkH+L
  artifact: /.*\.nupkg/
  draft: true
  on:
    branch: master