version: 3.1.6.{build}
skip_tags: true
image: Visual Studio 2017 Preview
configuration: Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

before_build: 
- ps: >-
    dotnet restore
    
    nuget restore

build: off

build_script: dotnet build -c "Release"

after_build: dotnet pack ".\src\Noobot.Toolbox\Noobot.Toolbox.csproj" --no-build --no-restore --output "..\..\nupkgs" -c "Release"

test: off

artifacts:
- path: nupkgs\*.nupkg

deploy:
- provider: GitHub
  auth_token:
    secure: C84vi0K9LH3m0DN0dITWoJ09qb3sAcyqqkHsWWUE8EAlC2Xj7p9G+VcPVDKqkH+L
  artifact: /.*\.nupkg/
  draft: true
  on:
    branch: build_fix